import * as Lucide from 'lucide-angular';

export abstract class IconBase {
  readonly icons = {
    FileIcon: Lucide.FileIcon,
    HomeIcon: Lucide.HomeIcon,
    MenuIcon: Lucide.MenuIcon,
    UserIcon: Lucide.UserIcon,
    UsersRoundIcon: Lucide.UsersRoundIcon,
    CirclePlus: Lucide.CirclePlus,
    // Iconos para login, registro y restablecimiento de contraseña
    MailIcon: Lucide.Mail,
    // Iconos para errores, éxito y alertas
    CheckCircleIcon: Lucide.CheckCircle,
    XCircleIcon: Lucide.XCircle,
    // Iconos para calculadora IMC y salud
    CalculatorIcon: Lucide.Calculator,
    HeartIcon: Lucide.Heart,
    InfoIcon: Lucide.Info,
    CheckIcon: Lucide.Check,
    ClockIcon: Lucide.Clock,
    SaladIcon: Lucide.Salad,
    // Iconos para seguridad y contraseñas
    LockIcon: Lucide.Lock,
    EyeIcon: Lucide.Eye,
    EyeOffIcon: Lucide.EyeOff,
    // Otros iconos útiles para la aplicación
    LogOutIcon: Lucide.LogOut,
    SettingsIcon: Lucide.Settings,
    ShieldIcon: Lucide.Shield,
    PhoneIcon: Lucide.Phone,
    CalendarIcon: Lucide.Calendar,
    PlusIcon: Lucide.Plus,
    MinusIcon: Lucide.Minus,
    TrashIcon: Lucide.Trash,
    ChevronRightIcon: Lucide.ChevronRight,
    ChevronLeftIcon: Lucide.ChevronLeft,
    ArrowRightIcon: Lucide.ArrowRight,
    ArrowLeftIcon: Lucide.ArrowLeft,
    PencilLineIcon: Lucide.PencilLine,
    StarIcon: Lucide.Star,
    BanIcon: Lucide.Ban,
    // Sección de sintomas
    DropletIcon: Lucide.Droplet,
    MoonIcon: Lucide.Moon,
    WeightIcon: Lucide.Weight,
    AppleIcon: Lucide.Apple,
    SmileIcon: Lucide.Smile,
    AlertTriangleIcon: Lucide.AlertTriangle,
    MehIcon: Lucide.Meh,
    AngryIcon: Lucide.Angry,
    FrownIcon: Lucide.Frown,
    LaughIcon: Lucide.Laugh,
    BatteryChargingIcon: Lucide.BatteryCharging,
    ActivityIcon: Lucide.Activity,
    BrainIcon: Lucide.Brain,
    WindIcon: Lucide.Wind,
    ThermometerIcon: Lucide.Thermometer,
    HeartPulseIcon: Lucide.HeartPulse,
    SquareActivityIcon: Lucide.SquareActivity,
    LoaderPinwheelIcon: Lucide.LoaderPinwheel,
    CigaretteIcon: Lucide.Cigarette,
    PillIcon: Lucide.Pill,
    BeerIcon: Lucide.Beer,
    TabletsIcon: Lucide.Tablets,
    StethoscopeIcon: Lucide.Stethoscope,
    AlertCircleIcon: Lucide.AlertCircle,
    DumbbellIcon: Lucide.Dumbbell,
    //Mitos
    GlassWaterIcon: Lucide.GlassWater,
    BedDoubleIcon: Lucide.BedDouble,
    SunIcon: Lucide.Sun,
    HeadphonesIcon: Lucide.Headphones,
  };
}
